name: Scrape + Deploy Pages (static)

on:
  schedule:
    - cron: "0 10,18 * * 1-5"   # dias úteis 10:00 e 18:00 UTC
  workflow_dispatch: {}

permissions:
  pages: write
  id-token: write
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm i
          fi

      - name: Show cookie presence
        run: |
          if [ -z "${FUNDAMENTUS_COOKIE}" ]; then
            echo "FUNDAMENTUS_COOKIE is EMPTY"
          else
            echo "FUNDAMENTUS_COOKIE is SET (len: ${#FUNDAMENTUS_COOKIE})"
          fi
        env:
          FUNDAMENTUS_COOKIE: ${{ secrets.FUNDAMENTUS_COOKIE }}

      - name: Run scraper
        env:
          FUNDAMENTUS_COOKIE: ${{ secrets.FUNDAMENTUS_COOKIE }}
        run: node scrape.js

      - name: List docs
        run: |
          echo "=== docs ==="; ls -la docs || true
          echo "=== head resultado.html ==="; head -n 5 docs/resultado.html || true
          echo "=== head resultado.csv ==="; head -n 5 docs/resultado.csv || true
          echo "=== head raw.html ==="; head -n 5 docs/raw.html || true

      - name: Ensure index + .nojekyll
        run: |
          mkdir -p docs
          [ -f docs/index.html ] || cat > docs/index.html <<'HTML'
          <meta charset="utf-8">
          <h1>fundamentus-proxy</h1>
          <ul>
            <li><a href="./resultado.html">resultado.html</a></li>
            <li><a href="./resultado.csv">resultado.csv</a></li>
            <li><a href="./raw.html">raw.html</a></li>
          </ul>
          HTML
          touch docs/.nojekyll

      - name: Fail if scrape missing
        run: |
          test -f docs/resultado.html
          test -f docs/resultado.csv

      - name: Upload artifact (docs)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
