name: Scrape Fundamentus

on:
  schedule:
    - cron: "0 10,18 * * 1-5"  # 10:00 e 18:00 UTC em dias úteis (ajuste ao seu gosto)
  workflow_dispatch: {}        # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Scrape
        env:
          FUNDAMENTUS_COOKIE: ${{ secrets.FUNDAMENTUS_COOKIE }}
        run: npm run scrape

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add docs/resultado.csv docs/resultado.html
          git commit -m "Update snapshot" || echo "Nada para commitar"
          git push
